### ISSUE TITLE
Typescript typedef fix

### ISSUE THREAD

**Issue by Sparkenstein** [kleisauke/wasm-vips#14]
Was just looking at this library, to be used in my react app with typescript. turns out the type definition that comes with library are like 
```ts
declare namespace vips { ... }
```

i.e. they are not exported. you need to export them so that the lib is usable in other TS projects.

```ts
export namespace vips
```

otherwise we get following error:

```sh
File 'x/node_modules/wasm-vips/lib/vips.d.ts' is not a module.ts(2306)
```

**Comment by kleisauke** [comment]
Ah, you're right. I only tested these type definitions within the wasm-vips playground, which somehow didn't require this. This has been fixed with commit https://github.com/kleisauke/wasm-vips/commit/372e5e345cf0c57b4866b44fad5568eac2823eef.

**Comment by kleisauke** [comment]
v0.0.3 is now available.
