### ISSUE TITLE
deno support

### ISSUE THREAD

**Issue by ImUrX** [kleisauke/wasm-vips#25]
it would be nice for this to happen :)
also found [this](https://github.com/emscripten-core/emscripten/issues/13190#issuecomment-1159204680)

**Comment by ImUrX** [comment]
sorry for being ignorant, didnt check on the closed issues. Could you maybe mention support on the readme?

**Comment by kleisauke** [comment]
Good idea! Commit 46be7510bfb7bd61f31e4cac9817e477360ba0d0 mentions that Deno is supported and includes an example on how to import it.
