### ISSUE TITLE
Is it possible to use wasm-vips without concurrency and workers?

### ISSUE THREAD

**Issue by lokiiarora** [kleisauke/wasm-vips#28]
Is it possible to have a custom build of wasm-vips without `SharedArrayBuffer` and Workers / concurrency ?
We wrap wasm-vips to build an internal texture compressor, it becomes slightly harder to package this as a library with the Worker Pattern.

**Comment by kleisauke** [comment]
Hi, did you see #18 ?

**Comment by lokiiarora** [comment]
Oh no !
I did not see this, so the baseline being currently, it is not possible right?

**Comment by kleisauke** [comment]
I think it's currently impossible to workaround that, and I'm not sure it's worth the effort if it could, since [`SharedArrayBuffer`](https://caniuse.com/sharedarraybuffer) is present in most major browser engines. It probably also affects performance in a negative way.

**Comment by lokiiarora** [comment]
Makes sense, thanks !
