### ISSUE TITLE
HEIC support

### ISSUE THREAD

**Issue by vadimkantorov** [kleisauke/wasm-vips#3]
Does libvips-wasm support HEIC decoding? From the [announcement](https://libvips.github.io/libvips/2020/09/01/libvips-for-webassembly.html) it's not very clear: JPG, PNG, TIFF, WebP are mentioned, but it's not clear if the list is exhaustive.

It would be very useful for creating an in-browser HEIC->JPG converter. Modern iPhone photos are in HEIC and Windows often has broken HEIC decoding.

**Comment by kleisauke** [comment]
Sorry for the delay, the list from the announcement is exhaustive (with the only exception that loading GIFs will soon be supported, see the [`vips-8.11`](https://github.com/kleisauke/wasm-vips/tree/vips-8.11) branch).

I do not intend to support HEIC (via libde265 and libheif) as it includes patent-encumbered HEVC-related logic. For the same reason, this format is also not supported in the pre-built binaries provided by [sharp](https://github.com/lovell/sharp) and [NetVips](https://github.com/kleisauke/net-vips).

**Comment by mikroskeem** [comment]
What would be the way to get HEIC working? I presume one of the steps are that I need to introduce libde265, and set `-DWITH_LIBDE265=1` in build.sh?
