### ISSUE TITLE
Consider using new libtiff build flags

### ISSUE THREAD

**Issue by CoenraadS** [kleisauke/wasm-vips#37]
With libtiff 4.5.0, some new build options are introduced which may help compile times:

https://gitlab.com/libtiff/libtiff/-/commit/1ab0e2696a368a556b793a0941b5365e4d9f56ef#87db583be5c13c1f7b3c958b10e03d67b6a2ca06_319_330

```
--disable-tools
--disable-tests
--disable-contrib
--disable-docs
```

**Comment by kleisauke** [comment]
Incorporated with commit 628f6fafb77c94f2b9dcd68df7eccb7fdd5f5b05, thanks for reporting!

**Comment by kleisauke** [comment]
... commit https://github.com/lovell/sharp-libvips/commit/f0fb81df4ad53385c1c7388fa2007994326b4ab0 and https://github.com/libvips/build-win64-mxe/commit/3c04aa7614496f66aebd56505a71ab97f5cc4244 also incorporates this. :)
