### ISSUE TITLE
Usage in Browser

### ISSUE THREAD

**Issue by smurrayatwork** [kleisauke/wasm-vips#4]
I've installed this npm package in a repo using storybook, as I'm trying to experiment with it in React but I'm unable to get it working in the browser. Of course, it downloads a version of the package for node use only, so I'm wondering how to get this working in a browser, since the files provided by the npm package use things specific to node.

I know the playground works, so do I have to grab a copy of this repo and build things locally?

**Comment by kleisauke** [comment]
The current v0.0.1 NPM package is only usable within a Node.js environment (for now). I still have to figure out how to distribute the web variant or check whether it is possible to use an multi-targeted output (one that can be used on both web and Node), as I don't want to blow the NPM package up too much (in terms of size).

As a potential workaround you could just download these files from the playground.
https://wasm-vips.kleisauke.nl/lib/vips.d.ts
https://wasm-vips.kleisauke.nl/lib/vips.js
https://wasm-vips.kleisauke.nl/lib/vips.wasm
https://wasm-vips.kleisauke.nl/lib/vips.worker.js

Or build it yourself in the source directory with `npm run build:web`.

**Comment by amittal-quot** [comment]
There does not seem be be any `npm run build:web` command
``` json
  "scripts": {
    "build": "docker build -t wasm-vips . && docker run --rm -v $(pwd):/src wasm-vips ./build.sh",
    "test:web": "serve -c test/unit/serve.json",
    "test:node": "cd test/unit && npm run test",
    "test": "npm run test:node",
    "bench:web": "serve -c test/bench/serve.json",
    "bench:node": "cd test/bench && npm run test",
    "bench": "npm run bench:node"
  },
```

**Comment by kleisauke** [comment]
The next version of wasm-vips will include the web variant in the NPM package using the following structure:
```bash
$ tree lib/ -h --dirsfirst
lib/
├── node-commonjs
│   ├── [ 199K]  vips.js
│   └── [ 3.0K]  vips.worker.js
├── node-es6
│   ├── [ 199K]  vips.mjs
│   └── [ 3.1K]  vips.worker.mjs
├── web
│   ├── [ 206K]  vips.js
│   ├── [ 4.7M]  vips.wasm
│   └── [ 2.3K]  vips.worker.js
├── [ 256K]  vips.d.ts
└── [ 4.7M]  vips.wasm

3 directories, 9 files
```
The `node-commonjs` and `node-es6` directories ensures that wasm-vips can be imported as both CommonJS and ES6 module on Node (the `web` variant will always be published as an ES6 module). Note that the resulting `web/vips.wasm` file is the same as `vips.wasm`, so the former will not be included in the NPM package (that also means that a user must copy `vips.wasm` to `web/` before it can be used in the browser).

@amittal-quot The `build:web` script was merged into the `build` script with commit https://github.com/kleisauke/wasm-vips/commit/53dd74e2db4db08a1ee69b7cbdc54537d8255375. You can just run `npm run build` to build for both web and Node.js environments.

**Comment by JoxC** [comment]
@kleisauke Thanks for your great work! 
When I run `npm run build` on Mac, I always got this:

> [ 80%] Linking CXX executable ../../../../lib/web/vips.js
> wasm-ld: error: unable to find library -lUSE_PTHREADS=1
> wasm-ld: error: unable to find library -lUSE_PTHREADS=1
> wasm-ld: error: unable to find library -lUSE_PTHREADS=1

I'm not familiar with Emscripten cross compile, could you help me figure out this ?

**Comment by kleisauke** [comment]
@JoxC It looks like [this Meson patch](https://github.com/kleisauke/wasm-vips/blob/71ee3942e14f58f95ab3c1f5441e197b89aa2110/build/patches/meson-emscripten.patch) was not applied during the build of the Docker image.
https://github.com/kleisauke/wasm-vips/blob/71ee3942e14f58f95ab3c1f5441e197b89aa2110/Dockerfile#L23-L25

Please can you open a new issue for this.

**Comment by blipk** [comment]
Hi.

I'm trying to get the web version of this working, I tried the npm module at first, but despite what your README says, after I've come here it's clear it doesn't include the web release version.

So I tried the files linked above, and I also tried building it myself with the docker file and I get this error stack:
![image](https://user-images.githubusercontent.com/45532845/140009324-5a2dc1f3-39af-4301-8489-c2cea8b92920.png)

I'm using npm and parcel-bundler to build a dist release, it handles other wasm libraries fine.

**Comment by blipk** [comment]
Ok, seems to be working now, rather than using import in my existing module I had to drop vips.js in a script tag.
```
  <script src="wasm-vips/vips.js"></script>
  <script src="index.js" type="module"></script>
```

I believe the parcel bundler was bundling incorrectly when it was `import`ed from index.js

Then I use it in my module like this:
```
var vips;
async function start() {
    vips = await Vips()
    console.log(vips)
}
start();
```

**Comment by blipk** [comment]
Is SVG loading supported? newFromBuffer throws `VipsForeignLoad: buffer is not in a known format`
I have seen other vips wrappers supporting this though

**Comment by kleisauke** [comment]
@blipk I'm glad it's working now. The README reflects the upcoming v0.0.2 release, which should arrive when libvips 8.12 is released. ES6 module import doesn't currently work on the web, as you noticed. I had to revert that with commit https://github.com/kleisauke/wasm-vips/commit/ba6f7eec2d5adbadd1282fc41af43d901cece097 to ensure compatibility with Firefox.

The difference between wasm-vips and the pre-built binaries provided by sharp (and NetVips) is that these dependencies are not (currently) compiled for WebAssembly:
- librsvg (support for loading SVG images)<sup>1</sup>
- libheif (support for loading and saving AVIF images)<sup>2</sup>
- libgsf (support for creating image pyramids with `dzsave`)
- liborc (improves the performance of the resize, blur and sharpen operations)<sup>3</sup>
- libimagequant (support for writing 8-bit palette-ised PNGs)<sup>4</sup>

<sup>1</sup>: Also requires: gdk-pixbuf, cairo, pixman, fontconfig, pango, freetype, harfbuzz, fribidi and libxml2.
<sup>2</sup>: Also requires: libaom.
<sup>3</sup>: Might not be needed in the future, see the [`simd`](https://github.com/kleisauke/wasm-vips/tree/simd) branch.
<sup>4</sup>: Will be included within the next release, see the [`gifsave`](https://github.com/kleisauke/wasm-vips/tree/gifsave) branch.

**Comment by blipk** [comment]
Thanks, I was confused as calling svgload was saying it doesnt exist if called with correct args, but if given extra args would give me an argument count error. The pre-emptive docs are a little confusing too.

I managed to use a canvas to convert SVG to png data URI, then fetch that to a blob, and then convert that to a uint8array to pass to newFromBuffer

**Comment by kleisauke** [comment]
v0.0.2 now available.
