### ISSUE TITLE
Does this work with `sharp`?

### ISSUE THREAD

**Issue by styfle** [kleisauke/wasm-vips#43]
There was an issue submitted to `sharp` requesting support for wasm ([see this issue](https://github.com/lovell/sharp/issues/3336)).

In that issue, the author links to this repo ([see this comment](https://github.com/lovell/sharp/issues/3336#issuecomment-1223732000)).

Is there a way to use `wasm-vips` with the `sharp` API? (probably needs ArrayBuffer input instead of file path)

**Comment by kleisauke** [comment]
Hello, did you see the notes in https://github.com/users/kleisauke/projects/1?pane=issue&itemId=13823822 and PR https://github.com/lovell/sharp/pull/3522?

**Comment by RReverser** [comment]
I should've linked that issue in my PR, didn't know there's one open :)
