### ISSUE TITLE
`heifsave` is not defined

### ISSUE THREAD

**Issue by saschanaz** [kleisauke/wasm-vips#44]
```js
import Vips from 'wasm-vips';

const vips = await Vips();

let im = vips.Image.newFromFile('test.4.jpg');
im.heifsave('testoutput.avif');
```

This fails on wasm-vips 0.0.4, perhaps some build flag is missing?

**Comment by atjn** [comment]
HEIF/AVIF is not supported in v0.0.4. It should work just fine [when v0.0.5 is released](https://github.com/kleisauke/wasm-vips/pull/36#pullrequestreview-1226584021).

For my projects, I have manually compiled wasm-vips with HEIF support, so I can keep working while waiting for an official release. Feel free to copy the custom release from my repository: https://github.com/atjn/easy-web-app-builder/blob/cbdf3b27e45c56b66324fdb393f69558e07bb4ed/wasm-vips-0.0.4%2Bb24ca0b.tgz

You can install the zip file directly by running `npm install wasm-vips-0.0.4+b24ca0b.tgz` , and you can even tell NPM to bundle this custom release with your project when you release new versions.

**Comment by saschanaz** [comment]
Awesome, thanks! I'll close this then 👍

**Comment by kleisauke** [comment]
v0.0.5 now available.
