### ISSUE TITLE
provide distribution artifacts for every new release and jpegli support

### ISSUE THREAD

**Issue by gemini133** [kleisauke/wasm-vips#73]
Hi kleisauke,
Could you provide artifacts for every new release? maybe zip them from github actions.
Also, is it possible to support jpegli instead of mozjpeg?  the former is better , at least in terms of compression ratio, from what I find, it's 30+% size saving.
Thanks in advance

**Comment by kleisauke** [comment]
Hi @gemini133,

> Could you provide artifacts for every new release? maybe zip them from github actions.

wasm-vips will only be distributed via [npmjs.com](https://www.npmjs.com/); there are currently no plans to distribute it through other channels.

> Also, is it possible to support jpegli instead of mozjpeg?

Please subscribe to https://github.com/lovell/sharp/issues/4018 for possible updates.

**Comment by gemini133** [comment]
thanks for quick reply

**Comment by gemini133** [comment]
I managed to build  wasm-vips with libjpegli. you can check out my fork gemini133/wasm-vips but I haven't updated it since then.
as for the comment, the libvips way, I believe it's just to replace the system jpeg.so file with jpegli's
