### ISSUE TITLE
Saving anything as PNG produces massive files

### ISSUE THREAD

**Issue by miloxeon** [kleisauke/wasm-vips#77]
Hi again!

When I convert a 3.8 MB JPEG image to PNG, the result is 12.4 MB. It doesn't depend on Q value: the size is the same for both Q = 100 and Q = 30. Here's my worker code:
```JS
import Vips from './vendor/vips-es6.js'
const vips = await Vips()

onmessage = async ({ data: { file } }) => {
	const image = vips.Image.newFromBuffer(await file.arrayBuffer()) // file is an image from input[type="file"]
	const params = { Q: 30 } // changing Q to 100 has no effect
	const blob = new Blob([image.writeToBuffer('.png', params)], { type: 'image/png' })
	image.delete()
	const url = URL.createObjectURL(blob)
	postMessage({ ok: true, url, name: file.name })
}
```

I feel like I'm missing something very simple. Plus, wasm-vips [supposedly includes libimagequant](https://github.com/kleisauke/wasm-vips/issues/65#issuecomment-2028630333) that is well-known for producing small PNG files.

How do I enable high-quality lossy compression?

**Comment by miloxeon** [comment]
Here are my files: [large-pngs.zip](https://github.com/user-attachments/files/17174128/large-pngs.zip)

**Comment by kleisauke** [comment]
You'll need to set `pallete` to `true` if you want to save to a palette-based (i.e. lossy) PNG.
```diff
@@ -3,7 +3,7 @@ const vips = await Vips()
 
 onmessage = async ({ data: { file } }) => {
   const image = vips.Image.newFromBuffer(await file.arrayBuffer()) // file is an image from input[type="file"]
-  const params = { Q: 30 } // changing Q to 100 has no effect
+  const params = { Q: 30, palette: true }
   const blob = new Blob([image.writeToBuffer('.png', params)], { type: 'image/png' })
   image.delete()
   const url = URL.createObjectURL(blob)
```
https://github.com/kleisauke/wasm-vips/blob/4702f7df3feeed3efcc07e904de2557a330fce18/lib/vips.d.ts#L8715-L8718

See also: https://www.libvips.org/API/current/VipsForeignSave.html#vips-pngsave.

Note that [sharp](https://github.com/lovell/sharp) automagically set this to `true` when you use `.png({ quality: 30 })`.
https://github.com/lovell/sharp/blob/v0.33.5/lib/output.js#L573-L577

**Comment by miloxeon** [comment]
Yes, that seems to do the trick. Thanks!
