### ISSUE TITLE
Fatal JavaScript out of memory on Deno

### ISSUE THREAD

**Issue by bavoco** [kleisauke/wasm-vips#81]
Really enjoying using this library, but lately I have trouble running the latest versions (0.0.9, 0.0.10) on Deno (versions 1.45.x, 1.46.x, 2.0.x)

Given:
```typescript
// @deno-types="https://cdn.jsdelivr.net/npm/wasm-vips/lib/vips.d.ts"
import Vips from 'https://cdn.jsdelivr.net/npm/wasm-vips/lib/vips-es6.js';

const vips = await Vips({
    dynamicLibraries: [],
});
```

The output is:
```
error: Uncaught (in worker "em-pthread")(in promise) RangeError: WebAssembly.Memory(): could not allocate memory
    at https://cdn.jsdelivr.net/npm/wasm-vips/lib/vips-es6.js:15:84
    at https://cdn.jsdelivr.net/npm/wasm-vips/lib/vips-es6.js:242:14

#
# Fatal JavaScript out of memory:...
```

Things I've tried:
- reducing the INITIAL_MEMORY:
```typescript
const vips = await Vips({
    dynamicLibraries: [],
    INITIAL_MEMORY: 512 * 1024 * 128,
});
```
- adding `--v8-flags=--max-old-space-size=4096`

Version 0.0.8 and before are working great.

**Comment by kleisauke** [comment]
I was able to reproduce the issue, and confirm that it only occurs with version 0.0.9 or later.

Commit https://github.com/kleisauke/emscripten/commit/67924ad25146e925cc8d43b46d81320a4b058389 fixes this, this will be in v0.0.11. Thanks for reporting this!

**Comment by kleisauke** [comment]
Upstream PR: https://github.com/emscripten-core/emscripten/pull/22778.

**Comment by kleisauke** [comment]
v0.0.10 is now available.
